const technologies = [
    { id: 1, title: "HTML", difficulty: "Easy", duration: 2, scope: ["web development"] },
    { id: 2, title: "CSS", difficulty: "Easy", duration: 2, scope: ["web development"] },
    { id: 3, title: "JavaScript", difficulty: "Medium", duration: 4, scope: ["web development"] },
    { id: 4, title: "TypeScript", difficulty: "Medium", duration: 3, scope: ["web development"] },
    { id: 5, title: "React", difficulty: "Medium", duration: 4, scope: ["web development"] },
    { id: 6, title: "Next.js", difficulty: "Medium", duration: 3, scope: ["web development"] },
    { id: 7, title: "Vue.js", difficulty: "Medium", duration: 3, scope: ["web development"] },
    { id: 8, title: "Angular", difficulty: "Hard", duration: 5, scope: ["web development"] },
    { id: 9, title: "Node.js", difficulty: "Medium", duration: 4, scope: ["backend", "web development"] },
    { id: 10, title: "Express.js", difficulty: "Medium", duration: 2, scope: ["backend"] },
    { id: 11, title: "MongoDB", difficulty: "Medium", duration: 3, scope: ["backend", "database"] },
    { id: 12, title: "MySQL", difficulty: "Medium", duration: 3, scope: ["backend", "database"] },
    { id: 13, title: "PostgreSQL", difficulty: "Medium", duration: 3, scope: ["backend", "database"] },
    { id: 14, title: "Firebase", difficulty: "Medium", duration: 2, scope: ["web development", "mobile development", "backend"] },
    { id: 15, title: "Docker", difficulty: "Hard", duration: 4, scope: ["devops"] },
    { id: 16, title: "Kubernetes", difficulty: "Hard", duration: 5, scope: ["devops"] },
    { id: 17, title: "AWS", difficulty: "Hard", duration: 6, scope: ["cloud", "devops"] },
    { id: 18, title: "Google Cloud", difficulty: "Hard", duration: 6, scope: ["cloud", "devops"] },
    { id: 19, title: "Azure", difficulty: "Hard", duration: 6, scope: ["cloud", "devops"] },
    { id: 20, title: "Git", difficulty: "Easy", duration: 1, scope: ["devops", "general"] },
    { id: 21, title: "GitHub", difficulty: "Easy", duration: 1, scope: ["devops", "general"] },
    { id: 22, title: "Tailwind CSS", difficulty: "Medium", duration: 2, scope: ["web development"] },
    { id: 23, title: "Bootstrap", difficulty: "Easy", duration: 2, scope: ["web development"] },
    { id: 24, title: "SASS/SCSS", difficulty: "Medium", duration: 2, scope: ["web development"] },
    { id: 25, title: "Redux", difficulty: "Medium", duration: 3, scope: ["web development"] },
    { id: 26, title: "Zustand", difficulty: "Medium", duration: 2, scope: ["web development"] },
    { id: 27, title: "Jest", difficulty: "Medium", duration: 2, scope: ["testing"] },
    { id: 28, title: "Cypress", difficulty: "Medium", duration: 2, scope: ["testing"] },
    { id: 29, title: "GraphQL", difficulty: "Medium", duration: 3, scope: ["backend", "web development"] },
    { id: 30, title: "REST API", difficulty: "Medium", duration: 2, scope: ["backend", "web development"] },
    { id: 31, title: "Python", difficulty: "Medium", duration: 4, scope: ["backend", "data science"] },
    { id: 32, title: "Django", difficulty: "Hard", duration: 4, scope: ["backend", "web development"] },
    { id: 33, title: "Flask", difficulty: "Medium", duration: 3, scope: ["backend"] },
    { id: 34, title: "Java", difficulty: "Hard", duration: 6, scope: ["backend", "mobile development"] },
    { id: 35, title: "Spring Boot", difficulty: "Hard", duration: 4, scope: ["backend"] },
    { id: 36, title: "C++", difficulty: "Hard", duration: 6, scope: ["general", "game development"] },
    { id: 37, title: "C#", difficulty: "Hard", duration: 4, scope: ["general", "game development"] },
    { id: 38, title: "Ruby on Rails", difficulty: "Medium", duration: 4, scope: ["backend"] },
    { id: 39, title: "Go", difficulty: "Medium", duration: 4, scope: ["backend"] },
    { id: 40, title: "Rust", difficulty: "Hard", duration: 6, scope: ["systems", "backend"] },
    { id: 41, title: "PHP", difficulty: "Medium", duration: 3, scope: ["web development", "backend"] },
    { id: 42, title: "Laravel", difficulty: "Medium", duration: 4, scope: ["web development", "backend"] },
    { id: 43, title: "Flutter", difficulty: "Medium", duration: 4, scope: ["mobile development"] },
    { id: 44, title: "React Native", difficulty: "Medium", duration: 4, scope: ["mobile development"] },
    { id: 45, title: "Swift", difficulty: "Hard", duration: 5, scope: ["mobile development"] },
    { id: 46, title: "Kotlin", difficulty: "Hard", duration: 5, scope: ["mobile development"] },
    { id: 47, title: "Unity", difficulty: "Hard", duration: 5, scope: ["game development"] },
    { id: 48, title: "Blender", difficulty: "Medium", duration: 4, scope: ["design", "game development"] },
    { id: 49, title: "Three.js", difficulty: "Hard", duration: 4, scope: ["web development", "3D graphics"] },
    { id: 50, title: "TensorFlow", difficulty: "Hard", duration: 6, scope: ["AI", "machine learning"] }
];


export { technologies }